name: Build and Release
on:
  push:
  workflow_dispatch:
jobs:
  build-debs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        src: [matchbox]
    steps:
      - uses: actions/checkout@v3
      - uses: jtdor/build-deb-action@6248b905520adc4cebd80b218db1ad5543eae4fa # v1.7.4
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          host-arch: arm64
          source-dir: ${{ matrix.src }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE
